services:
  nodered:
    depends_on:
        - grafana
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
        - TZ=Europe/Berlin
    volumes:
        - ./nodered-storage:/data
    networks:
      - traefik-servicenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.entrypoints=web-secure"
      - "traefik.http.routers.nodered.rule=Host(`nodered.example.invalid`)" # change hostname!
      - "traefik.http.routers.nodered.tls=true"
      - "traefik.http.routers.nodered.tls.certresolver=tlschallenge"
      - "traefik.http.routers.nodered.middlewares=secHeaders@file"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
  influxdb:
    image: influxdb:latest
    restart: unless-stopped
    volumes:
      - ./influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - traefik-servicenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.entrypoints=web-secure"
      - "traefik.http.routers.influxdb.rule=Host(`influxdb.example.invalid`)" # change hostname!
      - "traefik.http.routers.influxdb.tls=true"
      - "traefik.http.routers.influxdb.tls.certresolver=tlschallenge"
      - "traefik.http.routers.influxdb.middlewares=secHeaders@file"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    restart: unless-stopped
    volumes:
      - ./grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - traefik-servicenet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=web-secure"
      - "traefik.http.routers.grafana.rule=Host(`dashboard.example.invalid`)" # change hostname!
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=tlschallenge"
      - "traefik.http.routers.grafana.middlewares=secHeaders@file"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  traefik-servicenet:
    external: true
    name: traefik-servicenet
